//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.12 at 06:48:18 AM UTC 
//


package at.fhv.marketprice;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the at.fhv.marketprice package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _MarketPriceInformation_QNAME = new QName("http://www.example.org/MarketPriceInformationList", "marketPriceInformation");
    private final static QName _MarketPriceAtomPrice_QNAME = new QName("http://www.example.org/MarketPriceInformationList", "price");
    private final static QName _MarketPriceAtomOrdinalNumber_QNAME = new QName("http://www.example.org/MarketPriceInformationList", "ordinalNumber");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: at.fhv.marketprice
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MarketPriceInformation }
     * 
     */
    public MarketPriceInformation createMarketPriceInformation() {
        return new MarketPriceInformation();
    }

    /**
     * Create an instance of {@link MarketPriceAtom }
     * 
     */
    public MarketPriceAtom createMarketPriceAtom() {
        return new MarketPriceAtom();
    }

    /**
     * Create an instance of {@link MarketPriceList }
     * 
     */
    public MarketPriceList createMarketPriceList() {
        return new MarketPriceList();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MarketPriceInformation }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/MarketPriceInformationList", name = "marketPriceInformation")
    public JAXBElement<MarketPriceInformation> createMarketPriceInformation(MarketPriceInformation value) {
        return new JAXBElement<MarketPriceInformation>(_MarketPriceInformation_QNAME, MarketPriceInformation.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/MarketPriceInformationList", name = "price", scope = MarketPriceAtom.class)
    public JAXBElement<Integer> createMarketPriceAtomPrice(Integer value) {
        return new JAXBElement<Integer>(_MarketPriceAtomPrice_QNAME, Integer.class, MarketPriceAtom.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/MarketPriceInformationList", name = "ordinalNumber", scope = MarketPriceAtom.class)
    public JAXBElement<Integer> createMarketPriceAtomOrdinalNumber(Integer value) {
        return new JAXBElement<Integer>(_MarketPriceAtomOrdinalNumber_QNAME, Integer.class, MarketPriceAtom.class, value);
    }

}
